<?php
$jokeList = array( 
"How do fish get high? Seaweed.",
"What do you call a chicken crossing the road? Poultry in moton.",
"Why did the house go to the doctor? It was having window panes.",
"What is the difference between erotic and kinky? Erotic is using a feather.... kinky is using the whole  feather.",
"Why was ten scared of seven? Because seven ate nine.",
"Did you hear about the drunk frog? He barley hops!",
"What's the difference between a pygmy tribe and a high school girls track team? The pygmy tribe is a bunch of   cunning little runts.",
"Why didn't the number 4 get into the nightclub? Because he is 2 square.",
"What's the difference between roast beef and pea soup? Anyone can roast beef but nobody can pee soup!",
"It's not that the man did not know how to juggle, he just didn't have the balls to do it.",
"A drum and a symbol fall off a cliff",
"What do you call a woman that sets her bills on fire? Bernadette.",
"Why is the barn so noisy? Because the cows have horns.",
"Two fish swim down a river, and hit a wall. One says: 'Dam!'",
"What do you call a cow with no legs? Ground beef",
"What do get if you cross a snowman with a vampire? Frostbite!",
"What did the blanket say as it fell off the bed? Oh sheet!",
"Why was the javascript developer sad? Because he didn't Node how to Express himself.",
"What's 6 inches long, 2 inches wide and drives women wild? a $100 bill!",
"Why did the crow land on the telephone pole? He wanted to make a long distance caw.",
"I'm reading a book about anti-gravity. It's impossible to put down.",
"What do you get when you cross a rabbit with a waterhose? Hare spray.",
"What are the best kind of letters to read in hot weather? Fan mail.",
"What sound does a nut make when it sneezes? Cashew!",
"What's red and bad for your teeth? A Brick.",
"What's orange and sounds like a parrot? A Carrot.",
"I'm glad I know sign language, it's pretty handy.",
"Two guys walk into a bar. You'd think the second one would have ducked.",
"How do you count cows? With a cowculator.",
"Why is it hard to make puns for kleptomaniacs? They are always taking things literally.",
"What is Napoleon's favorite part of a chicken? The Boney-Part!",
"What do you call a fake noodle?  An impasta",
"What happens when you drop a piano down a mine shaft? A minor B-flat!",
"What happens to a frog's car when it breaks down? It gets toad.",
"What does a leper say before he farts? I don't know, but probably not 'pull my finger'.",
"Two fish in a tank. One looks to the other and says 'Can you even drive this thing???'",
"Did you hear about the guy whose whole left side was cut off? He's all right now.",
"What do you call a fish with no eyes? A fsh.",
"What do you call a cow with two legs? Lean beef.",
"How did the hipster burn the roof of his mouth? He ate the pizza before it was cool.",
"Did you hear about the Mexican train killer?  He had locomotives",
"I wondered why the baseball was getting bigger. Then it hit me.",
"Why are ghosts bad liars? Because you can see right through them.",
"My friend's bakery burned down last night. Now his business is toast.",
"What is a centipedes's favorite Beatle song?  I want to hold your hand, hand, hand, hand...",
"Why shouldn't you write with a broken pencil? Because it's pointless!",
"What do you get when you mix human dna with a goats'? Banned from the petting zoo.",
"How many tickles does it take to tickle an octupus? Ten-tickles!", 
"What is the difference between snowmen and snowwomen? Snowballs.",
"I used to be a banker, but I lost interest.",
"How do you make holy water? Boil the hell out of it.",
"Why are pirates called pirates? Because they arrr!",
"What does a pirate pay for his corn? A buccaneer!",
"Why do seagulls fly over the sea? Because they aren't bay-gulls!",
"What do you call a fish with no eyes? fsh!",
"What is the hardest part about sky diving? The ground.",
"What's funnier than a monkey dancing with an elephant? Two monkeys dancing with an elephant.",
"What kind of bees produce milk? Boobies!",
"Why do mermaid wear sea-shells? Because b-shells are too small.",
"Why couldn't the kid see the pirate movie? Because it was rated arrr!",
"What do you get when you cross a chicken with a skunk? A fowl smell!",
'A mexican magician tells the audience he will disappear on the count of three. He says, "Uno, dos," and then  *POOF* he disappeared whatout a tres!',
"Can a kangaroo jump higher than the Empire State Building? Of course. The Empire State Building can't jump.",
"Why are fish easy to weigh? Because they have their own scales.",
"How did Darth Vader know what Luke was getting for Christmas? He felt his presents.",
"I want a job cleaning mirrors. It's something I could really see myself doing.",
);
?>
