<?php
$jokeList = array(
"Yo momma so fat she leaves footsteps in concrete",
"Yo momma is so fat when she was walking on the street her belly button was sticking out everybody started saying, hey look a third nipple!",
"Yo momma so fat when she went to McDonalds they offered her a group discount",
"Yo momma so fat, when she entered a fat contest, she came in first, second, and third.",
"Your momma so fat she doesn't need the internet; she's already world wide",
"Yo momma so fat God could not even lift her spirit",
"Yo momma so fat she got a parking ticket for standing at a crosswalk",
"Yo momma so fat not even Dora can explore her",
"Yo momma so fat, her shirts come in three sizes: Large, Extra Large, and OH MY GOD, IT'S COMING!",
"Your momma is so fat you feed on her junk",
"Yo momma is so fat a truck hit her and she said, Hey who threw that rock?",
"Yo momma is so fat when she fell in love, she broke it.",
"Yo momma so fat when she saw a bus driving down the road she said come back Twinkie",
"Yo momma so fat she stepped on the scale and it said one person at the time",
"Yo momma so fat, her stomach gets home 15 minutes before she does.",
"Yo momma is so fat her blood type is Ragu",
"Yo momma so fat she broke your family tree.",
"Yo momma so fat the last time she saw 90210 was on a scale",
"Yo momma's so fat when she made a YouTube account the entire network crashed.",
"Yo momma so fat that when she was born, she gave the hospital stretch marks.",
"Yo momma is so fat people thought her butt hole was a black hole.",
"Yo momma is so fat every time she tries to hide she is hiding that object that she is trying to hide by",
"Yo momma so fat she's got more Chins than a Hong Kong phone book.",
"Yo momma so fat she has more rolls than a bakery",
"Yo momma so fat when she goes swimming the whales start singing We are Family",
"Yo momma is so fat that on halloween she says trick or meatloaf",
"Yo momma's so fat the only alphabet she knows is her KFC's",
"Yo momma is so fat, that when she steps on a scale it says to be continued.",
"Yo momma so fat when she jogs she leaves pot holes",
"Yo momma so fat she's on both sides the family",
"Yo momma so fat when she tossed in her sleep she woke up in another time zone",
"Yo momma is so fat when I killed her in Call of Duty I got a five kill scorestreak.",
"Yo momma is so fat when she tried to go to McDonalds she tripped over Wendys and landed on Burger King",
"Yo momma so fat when she burped New Orlean thought Katrina came back to finish the job",
"Yo momma so fat she sat on a rainbow and popped Skittles out",
"Yo momma so fat when she wears one of those X jackets, helicopters try to land on her.",
"Yo momma is so fat that Weight Watchers said I give up",
"Yo momma so fat she sat on Wal-Mart and lowered the prices",
"Yo momma is so fat she can be my bear",
"Yo momma so fat when she dances at a concert the whole band skips.",
"Yo momma so fat when God said let it be light he told your momma to move",
"Yo mommas so fat everytime she turns around its her birthday",
"Yo momma so fat she don't fit in this joke",
"Yo momma so fat she wore a yellow raincoat and people yelled Taxi!",
"Yo momma so fat Mount Everest tried to climb her",
"Yo momma so fat that she fell over and rocked herself to sleep trying to get up",
"Yo momma so fat I had to take a train and two buses just to get on the her good side.",
"Yo momma so fat when she got hit by a bus she said who threw that rock",
"Yo momma is so fat, she got arrested at the airport for ten pounds of crack",
"Yo momma so fat she was diagnosed with flesh eating bacteria and the doctor gave her 87 years to live",
"Yo momma so fat, it takes her two trips to haul ass",
"Yo momma so fat when she walked across the street, someone said,\"Hey, the wooly mammoths are back!!\"",
"Yo momma is so fat were in her right now",
"Yo' mommas so fat that when she walked by the TV set I missed 3 seasons of Laguna Beach",
"Yo momma so fat, she can't even jump to a conclusion.",
"Yo momma is so fat if she buys a fur coat, a species will be extinct.",
"Yo momma so fat, to get her pregnant your dad had to roll her in flour and look for the wet spot.",
"Yo momma is so fat every time she sits down they add another country to the map",
"Yo momma so fat, you could slap her butt and ride the waves.",
"Yo momma's so fat she went to japan and Godzilla said DAMN and ran away.",
"Yo momma so fat Bill Gates couldn't pay for her liposuction",
"Yo momma so fat her beeper went off and people thought she was backing up.",
"Yo momma so fat she stepped on a Nintendo Gamecube and turned it into a Gameboy",
"Yo momma so fat it aint funny",
"Yo momma so fat, one day she was wearing a pair of yellow pants, and when she bent over the ass split open and 2 guys got in thinking it was a yellow cab!",
"Yo momma so fat when she fell no one laughed but the ground started cracking up",
"Yo momma so fat when she goes camping the bears hide their food",
"Yo momma so fat when she stepped on the scale it came up with my phone number",
"Yo momma so dumb someone said it was chilly outside and she ran out with a bowl and spoon!",
"Yo Momma so fat her IUD picks up radio free Europe",
"Yo momma is so fat, her diet pills say M & M",
"Yo mommas so fat when she went to her wedding the people sang the song \"here comes the bride so fat and wide\"",
"Yo momma so fat she put on her lipstick with a paint-roller.",
"Yo momma so fat I took a picture of her last Christmas and its still printing",
"Yo momma so fat she left the house in high heels and when she came back she had on flipflops",
"Yo momma so fat when she went to the circus the little girl asked if she could ride the elephant",
"Yo momma so fat that when she sits around the house, she sits around the house.",
"Yo momma so fat when she went to the movies she sat by everybody",
"Yo momma so fat you have to grease the door frame and hold a twinkie on the other side just to get her through.",
"Yo mommas so fat when she went to her wedding the people sang the song \"here comes the bride so fat and wide\"",
"Yo momma so fat she fell in a whirlpool and got stuck",
"Yo momma is so fat when she jumped in the air she got stuck",
"Yo momma's so fat, I got lost after running around her.",
"Yo momma so ugly she gotta sneak up on the water fountain to get a drink!",
"Yo momma so fat when she plays hop scotch she goes Chicago, New York, L.A.",
"Yo momma so fat, that the Twinkies revolve around her.",
"Yo momma so fat she sat on the beach and Greenpeace threw her in.",
"Yo momma so fat when she stepped on a scale Buzz Lightyear came out and said infinity and beyond!",
"Yo momma so fat not even a Twinkie would get her off the couch, even while a crane tries to help her",
"Yo mommas so fat when she went to her wedding the people sang the song \"here comes the bride so fat and wide\"",
"Yo momma so fat when she walked across the street, someone said,\"Hey, the wooly mammoths are back!!\"",
"Yo momma so fat she sat on a quarter and a booger shot out of George Washington's nose.",
"Yo mommas so fat when she went to her wedding the people sang the song \"here comes the bride so fat and wide\"",
"Yo momma so fat when she was standing on the corner a cop came along and told her to break it up",
"Yo momma so fat when she walked across the street, someone said,\"Hey, the wooly mammoths are back!!\"",
"Your momma is so fat people called her a wild hog",
"Yo momma is so fat that she uses the Great Wall of China as a belt",
"Yo momma so fat they changed one size fits all to one size fits most"
);
$joke = $jokeList[array_rand($jokeList)];
?>
